fn main {
    let _ = @m_0_0_0_0.f
    let _ = @m_0_0_0_1.f
    let _ = @m_0_0_1_0.f
    let _ = @m_0_0_1_1.f
    let _ = @m_0_1_0_0.f
    let _ = @m_0_1_0_1.f
    let _ = @m_0_1_1_0.f
    let _ = @m_0_1_1_1.f
    let _ = @m_1_0_0_0.f
    let _ = @m_1_0_0_1.f
    let _ = @m_1_0_1_0.f
    let _ = @m_1_0_1_1.f
    let _ = @m_1_1_0_0.f
    let _ = @m_1_1_0_1.f
    let _ = @m_1_1_1_0.f
    let _ = @m_1_1_1_1.f
    println("ok")
}
