// moon: The build system and package manager for MoonBit.
// Copyright (C) 2024 International Digital Economy Academy
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// For inquiries, you can contact us via e-mail at jichuruanjian@idea.edu.cn.

//! Constructs the build plan from the given build conditions, including
//! necessary pre-calculations.
//!
//! # Notes
//!
//! This module handles a different thing from the package dependency graph
//! generated by [`crate::solve`]. `solve` mainly constructs a dependency graph
//! that is not affected by what we're actually building, nor does it cares
//! about what actions are actually carried out on the dependency graph (like
//! check, build or test).
//!
//! In contrast, this module generates the actual build plan from a list of
//! requested artifacts. It selects their provider actions and expands
//! transitive artifact requirements; irrelevant packages and actions are not
//! included.
//!
//! The result of this module is analogous to Rust Cargo's [Compile unit graph][cu].
//! The reason why this is two graphs here in MoonBuild and only one graph in
//! Cargo is because our build procedure is a little more verbose than Cargo.
//!
//! # Precalculations
//!
//! This module pre-calculates shared information needed during build, including
//! file lists, hard-to-compute flags, and various configurations. The later
//! lowering pass is then merely just a dumb translation from existing config
//! and flags.
//!
//! [cu]: https://github.com/rust-lang/cargo/blob/master/src/cargo/core/compiler/unit.rs

use std::{
    collections::{HashMap, HashSet},
    ffi::OsStr,
    fmt::Write,
    path::{Path, PathBuf},
};

use indexmap::IndexSet;
use log::{debug, info};
use moonutil::{
    build_options::RunMode,
    compiler_flags::{CompilerPaths, Toolchain},
    cond_expr::OptLevel,
    resolution::ModuleId,
    target::TargetBackend,
    user_log::UserLog,
};
use sha2::{Digest, Sha256};
use tracing::instrument;

use crate::{
    ResolveOutput,
    model::{
        BackendConfig, BuildPlanNode, BuildTarget, NativeTarget, OperatingSystem, PackageId,
        TccRunConfig,
    },
    pkg_name::PackageFQNWithSource,
    prebuild::PrebuildOutput,
};

mod action;
mod artifact;
mod builders;
mod constructor;
mod package_prebuild;

pub(crate) use action::BuildAction;
pub use artifact::ArtifactKey;
use artifact::ArtifactPlan;
pub(crate) use artifact::package_file_key;
use constructor::BuildPlanConstructor;
pub use package_prebuild::PrebuildInfo;
pub(crate) use package_prebuild::{PackagePrebuildAction, PackagePrebuildPlan};

/// A build plan of actions and the artifacts that connect them.
///
/// Build-plan nodes identify actions. Every dependency names a logical artifact
/// and is resolved through that artifact's unique provider. The plan also
/// stores the metadata required to lower each action.
#[derive(Default)]
pub struct BuildPlan {
    /// Planned backend actions, in stable insertion order.
    actions: IndexSet<BuildPlanNode>,

    /// Logical artifacts provided and required by planned actions.
    artifacts: ArtifactPlan,

    /// The map of build target to its files and metadata.
    /// Used by nodes that require access to the raw MoonBit source files, like
    /// `Check`, `BuildCore`, `GenerateTestInfo` and `Format`.
    ///
    /// The following maps contain metadata needed for different types of build
    /// nodes. For each node present in the final graph, its metadata must
    /// already be present in the map.
    build_target_infos: HashMap<BuildTarget, BuildTargetInfo>,

    /// The map of build target to the metadata it needs when linking core
    link_core_info: HashMap<BuildTarget, LinkCoreInfo>,

    /// The map of build target to the C stubs information
    c_stubs_info: HashMap<PackageId, BuildCStubsInfo>,

    /// The map of build target to the information needed to make it executable
    make_executable_info: HashMap<BuildTarget, MakeExecutableInfo>,

    /// The resolved dsymutil executable, when the plan generates dSYM bundles.
    dsymutil: Option<PathBuf>,

    /// The information needed to build the native runtime library.
    runtime_info: Option<BuildRuntimeInfo>,

    /// Backend-independent package file-generation actions.
    package_prebuild: PackagePrebuildPlan,

    /// The concrete `.mbti` input selected for each planned virtual contract.
    virtual_contract_inputs: HashMap<PackageId, PathBuf>,

    /// The map of build target to its bundle information
    bundle_info: HashMap<ModuleId, BuildBundleInfo>,

    /// Logical results requested by the caller, in request order.
    requested_artifacts: IndexSet<ArtifactKey>,
}

impl BuildPlan {
    /// Get the list of nodes that **the given node depends on**.
    pub fn dependency_nodes(
        &self,
        node: BuildPlanNode,
    ) -> impl Iterator<Item = BuildPlanNode> + '_ {
        let mut seen = HashSet::new();
        self.artifact_dependencies(node)
            .map(|(provider, _)| provider)
            .filter(move |dependency| seen.insert(*dependency))
    }

    pub(crate) fn artifact_dependencies(
        &self,
        node: BuildPlanNode,
    ) -> impl Iterator<Item = (BuildPlanNode, ArtifactKey)> + '_ {
        self.artifacts.dependencies(node)
    }

    pub(crate) fn provided_artifacts(
        &self,
        node: BuildPlanNode,
    ) -> impl Iterator<Item = ArtifactKey> + '_ {
        self.artifacts.provided_by(node).cloned()
    }

    pub(crate) fn artifact_provider(&self, artifact: &ArtifactKey) -> BuildPlanNode {
        self.artifacts
            .provider(artifact)
            .expect("requested artifact should have a provider")
    }

    pub fn requested_artifacts(&self) -> impl Iterator<Item = &ArtifactKey> {
        self.requested_artifacts.iter()
    }

    /// Get build target information for the given target.
    pub fn get_build_target_info(&self, target: &BuildTarget) -> Option<&BuildTargetInfo> {
        self.build_target_infos.get(target)
    }

    /// Get link core information for the given target.
    pub fn get_link_core_info(&self, target: &BuildTarget) -> Option<&LinkCoreInfo> {
        self.link_core_info.get(target)
    }

    /// Get C stubs information for the given target.
    pub fn get_c_stubs_info(&self, target: PackageId) -> Option<&BuildCStubsInfo> {
        self.c_stubs_info.get(&target)
    }

    /// Get make executable information for the given target.
    pub fn get_make_executable_info(&self, target: &BuildTarget) -> Option<&MakeExecutableInfo> {
        self.make_executable_info.get(target)
    }

    /// Get the resolved dsymutil executable.
    pub fn get_dsymutil(&self) -> Option<&Path> {
        self.dsymutil.as_deref()
    }

    /// Get runtime library build information.
    pub fn get_runtime_info(&self) -> Option<&BuildRuntimeInfo> {
        self.runtime_info.as_ref()
    }

    pub(crate) fn package_prebuild_plan(&self) -> &PackagePrebuildPlan {
        &self.package_prebuild
    }

    pub(crate) fn virtual_contract_input(&self, package: PackageId) -> Option<&Path> {
        self.virtual_contract_inputs
            .get(&package)
            .map(PathBuf::as_path)
    }

    /// Get bundle information for the given module.
    pub fn bundle_info(&self, module_id: ModuleId) -> Option<&BuildBundleInfo> {
        self.bundle_info.get(&module_id)
    }

    pub fn all_nodes(&self) -> impl Iterator<Item = BuildPlanNode> + '_ {
        self.actions
            .iter()
            .copied()
            .chain(self.package_prebuild.nodes())
    }

    pub fn node_count(&self) -> usize {
        self.actions.len() + self.package_prebuild.action_count()
    }
}

#[cfg(test)]
impl BuildPlan {
    pub(crate) fn test_add_node(&mut self, node: BuildPlanNode) {
        assert!(!package_prebuild::is_package_prebuild_node(node));
        self.actions.insert(node);
    }

    pub(crate) fn test_request_artifact(&mut self, artifact: ArtifactKey) {
        self.requested_artifacts.insert(artifact);
    }

    pub(crate) fn test_require_artifact(&mut self, consumer: BuildPlanNode, artifact: ArtifactKey) {
        self.actions.insert(consumer);
        self.artifacts.require(consumer, artifact);
    }

    pub(crate) fn test_provide_artifact(&mut self, provider: BuildPlanNode, artifact: ArtifactKey) {
        if !package_prebuild::is_package_prebuild_node(provider) {
            self.actions.insert(provider);
        }
        self.artifacts.provide(provider, artifact);
    }

    pub(crate) fn test_insert_build_target_info(
        &mut self,
        target: BuildTarget,
        info: BuildTargetInfo,
    ) {
        self.build_target_infos.insert(target, info);
    }

    pub(crate) fn test_insert_moonlex_prebuild(
        &mut self,
        package: PackageId,
        index: u32,
        input: PathBuf,
        output: PathBuf,
    ) {
        self.package_prebuild
            .insert_moonlex(package, index, input, output);
    }

    pub(crate) fn test_insert_moonyacc_prebuild(
        &mut self,
        package: PackageId,
        index: u32,
        input: PathBuf,
        output: PathBuf,
    ) {
        self.package_prebuild
            .insert_moonyacc(package, index, input, output);
    }

    pub(crate) fn test_insert_link_core_info(&mut self, target: BuildTarget, info: LinkCoreInfo) {
        self.link_core_info.insert(target, info);
    }

    pub(crate) fn test_insert_c_stubs_info(&mut self, package: PackageId, info: BuildCStubsInfo) {
        self.c_stubs_info.insert(package, info);
    }

    pub(crate) fn test_insert_make_executable_info(
        &mut self,
        target: BuildTarget,
        info: MakeExecutableInfo,
    ) {
        self.make_executable_info.insert(target, info);
    }

    pub(crate) fn test_insert_dsymutil(&mut self, dsymutil: PathBuf) {
        self.dsymutil = Some(dsymutil);
    }

    pub(crate) fn test_insert_runtime_info(&mut self, info: BuildRuntimeInfo) {
        self.runtime_info = Some(info);
    }
}

/// Common information about a moonbit package being built
#[derive(Debug)]
pub struct BuildTargetInfo {
    /// Regular compilation files
    pub(crate) regular_files: Vec<PathBuf>,
    /// Verification helper files (`.mbtp`) for this target.
    pub(crate) mbtp_files: Vec<PathBuf>,

    /// Whitebox test files. Separated so determine whether the whitebox test is
    /// needed.
    ///
    /// TODO: suboptimal design. Better not populate unused build target info.
    pub(crate) whitebox_files: Vec<PathBuf>,

    /// Files that needs their doctests extracted instead of regular compilation.
    pub(crate) doctest_files: Vec<PathBuf>,

    /// The final list of warnings to pass to the compiler
    pub(crate) warn_list: Option<String>,

    /// Whether the target is designated by the user to not generate module interface.
    pub(crate) specified_no_mi: bool,

    /// The patch file to supply to this package
    pub(crate) patch_file: Option<PathBuf>,

    /// The Why3 configuration file to supply to proof commands.
    pub(crate) why3_config: Option<PathBuf>,

    /// The directory containing the selected proof prelude provider.
    pub(crate) proof_prelude: PathBuf,

    /// Check the `.mi` file against the given target. Used in virtual packages.
    /// Also implies that the target must not generate a `.mi` file.
    pub(crate) check_mi_against: Option<BuildTarget>,
    // we currently don't need this, as it's controlled by build-wise options
    // /// Whether compiling this target needs the standard library
    // pub std: bool,

    // we currently don't need this, as it's directly copied from mod.json.
    // pub is_main: bool,

    // Emit --enable-value-tracing if true
    pub(crate) value_tracing: bool,
}

impl BuildTargetInfo {
    pub fn files(&self) -> impl Iterator<Item = &Path> {
        self.regular_files
            .iter()
            .chain(self.whitebox_files.iter())
            .map(|x| x.as_path())
    }

    pub fn doctest_files(&self) -> impl Iterator<Item = &Path> {
        self.doctest_files.iter().map(|x| x.as_path())
    }

    pub fn mbtp_files(&self) -> impl Iterator<Item = &Path> {
        self.mbtp_files.iter().map(|x| x.as_path())
    }

    pub fn no_mi(&self) -> bool {
        self.specified_no_mi
    }
}

#[derive(Debug)]
pub struct LinkCoreInfo {
    /// The targets in **initialization order**.
    pub(crate) linked_order: Vec<BuildTarget>,

    /// Whether this package overwrites `moonbitlang/core/abort`.
    ///
    /// This is needed since `abort` is a prebuilt package, and needs special
    /// treatment to not be rebuilt when building user code.
    ///
    /// MAINTAINERS: When touching this part again, check if there's a better way to do this.
    pub abort_overridden: bool,
    // we currently don't need this, as it's controlled by build-wise options
    // /// Whether linking this target needs the standard library
    // pub std: bool,
}

#[derive(Debug)]
pub struct BuildCStubsInfo {
    /// The effective native toolchain for compiling the C stubs
    pub(crate) effective_native_toolchain: Toolchain,
    /// Additional flags to pass to the C compiler when compiling the C stubs
    pub(crate) cc_flags: Vec<String>,
    /// Additional flags to pass to the linker (TCC only)
    #[allow(unused)]
    pub(crate) link_flags: Vec<String>,
    /// Identity of the ordered static archive member list.
    ///
    /// This is only needed for archivers that update an existing archive.
    pub(crate) static_archive_fingerprint: Option<String>,
}

#[derive(Debug)]
pub struct MakeExecutableInfo {
    /// The effective native toolchain for this executable step
    pub(crate) effective_native_toolchain: Toolchain,
    /// The flags to pass to the C compiler when compiling the package itself
    pub(crate) c_flags: Vec<String>,
    /// The flags to pass to the C compiler driver when linking the executable
    pub(crate) link_flags: Vec<String>,
    /// The C stub targets to link with.
    pub(crate) link_c_stubs: Vec<PackageId>,
}

#[derive(Debug)]
pub struct BuildRuntimeInfo {
    /// The effective native toolchain for compiling the runtime library.
    pub(crate) effective_native_toolchain: Toolchain,
    /// Runtime C translation units shipped by the selected MoonBit toolchain.
    pub(crate) source_files: Vec<PathBuf>,
    /// Prebuilt objects selected as additional static archive members.
    pub(crate) simdutf_objects: Vec<PathBuf>,
    /// Identity of the ordered static archive member list.
    ///
    /// Shared-runtime builds do not create a static archive and leave this unset.
    pub(crate) static_archive_fingerprint: Option<String>,
}

fn runtime_archive_fingerprint(source_files: &[PathBuf], external_objects: &[PathBuf]) -> String {
    archive_member_fingerprint(
        source_files
            .iter()
            .map(|source| {
                (
                    0,
                    source
                        .file_stem()
                        .expect("runtime source should have a file stem"),
                )
            })
            .chain(external_objects.iter().map(|object| {
                (
                    1,
                    object
                        .file_name()
                        .expect("runtime archive member should have a file name"),
                )
            })),
    )
}

fn c_stub_archive_fingerprint(source_files: &[PathBuf]) -> String {
    archive_member_fingerprint(source_files.iter().map(|source| {
        (
            0,
            source
                .file_stem()
                .expect("C stub source should have a file stem"),
        )
    }))
}

fn archive_member_fingerprint<'a>(members: impl IntoIterator<Item = (u8, &'a OsStr)>) -> String {
    let mut hash = Sha256::new();
    for (kind, member) in members {
        let member = member.as_encoded_bytes();
        hash.update([kind]);
        hash.update((member.len() as u64).to_le_bytes());
        hash.update(member);
    }

    let digest = hash.finalize();
    let mut fingerprint = String::with_capacity(16);
    for byte in &digest[..8] {
        write!(&mut fingerprint, "{byte:02x}").expect("writing to a String cannot fail");
    }
    fingerprint
}

#[cfg(test)]
mod runtime_archive_fingerprint_tests {
    use super::*;

    #[test]
    fn fingerprint_tracks_ordered_members() {
        let sources = [PathBuf::from("runtime/a.c"), PathBuf::from("runtime/b.c")];
        let relocated = [
            PathBuf::from("other/runtime/a.c"),
            PathBuf::from("other/runtime/b.c"),
        ];
        let simd = [PathBuf::from("lib/simdutf.o")];
        let fingerprint = runtime_archive_fingerprint(&sources, &simd);

        assert_eq!(fingerprint, runtime_archive_fingerprint(&relocated, &simd));
        assert_ne!(
            fingerprint,
            runtime_archive_fingerprint(&sources[..1], &simd)
        );
        assert_ne!(fingerprint, runtime_archive_fingerprint(&sources, &[]));
        assert_ne!(
            fingerprint,
            runtime_archive_fingerprint(&[sources[1].clone(), sources[0].clone()], &simd)
        );
        assert_eq!(fingerprint.len(), 16);
    }

    #[test]
    fn c_stub_fingerprint_tracks_logical_members() {
        let sources = [PathBuf::from("src/a.c"), PathBuf::from("src/b.c")];
        let relocated = [PathBuf::from("other/a.c"), PathBuf::from("other/b.c")];
        let fingerprint = c_stub_archive_fingerprint(&sources);

        assert_eq!(fingerprint, c_stub_archive_fingerprint(&relocated));
        assert_ne!(fingerprint, c_stub_archive_fingerprint(&sources[..1]));
        assert_ne!(
            fingerprint,
            c_stub_archive_fingerprint(&[sources[1].clone(), sources[0].clone()])
        );
    }

    #[cfg(unix)]
    #[test]
    fn fingerprint_preserves_non_utf8_member_identity() {
        use std::{ffi::OsString, os::unix::ffi::OsStringExt};

        let first = PathBuf::from("runtime").join(OsString::from_vec(vec![b'a', 0x80, b'.', b'c']));
        let second =
            PathBuf::from("runtime").join(OsString::from_vec(vec![b'a', 0x81, b'.', b'c']));

        assert_ne!(
            runtime_archive_fingerprint(&[first], &[]),
            runtime_archive_fingerprint(&[second], &[])
        );
    }
}

/// Metadata about bundling the build output of different targets together.
pub struct BuildBundleInfo {
    /// The targets to bundle into the final bundle.
    pub(crate) bundle_targets: Vec<BuildTarget>,
}

/// Represents the environment in which the build is being performed.
pub struct BuildEnvironment {
    // FIXME: Target backend should go into the solver, not here
    pub backend: BackendConfig,
    pub opt_level: OptLevel,
    pub action: RunMode,
    pub debug_symbols: bool,
    pub os: OperatingSystem,
    /// Toolchain include/lib paths selected for native-oriented backends.
    pub compiler_paths: Option<CompilerPaths>,
    /// Whether compiling requires the standard library.
    ///
    /// MAINTAINERS: Potentially useful to move this to per-package/module.
    pub std: bool,
    /// Commandline_level warnings to enable/disable
    pub warn_list: Option<String>,
}

impl BuildEnvironment {
    pub(crate) fn target_backend(&self) -> TargetBackend {
        self.backend.target_backend()
    }

    pub(crate) fn direct_native_target(&self) -> Option<NativeTarget> {
        self.backend.direct_native_target()
    }

    pub(crate) fn tcc_run(&self) -> Option<&TccRunConfig> {
        self.backend.tcc_run()
    }
}

/// How package-level prebuild participates in this plan.
///
/// Package-level prebuild includes custom `pre-build` rules, `moonlex`, and
/// `moonyacc`. Binary dependencies must already contain their generated
/// outputs, so their internal compatibility build consumes existing outputs
/// instead of running any of these rules.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub enum PackagePrebuildPolicy {
    #[default]
    Run,
    ConsumeExistingOutputs,
}

/// Command-specific directives provided alongside requested artifacts.
#[derive(Debug)]
pub struct InputDirective {
    /// Set `no_mi=true` for the given package.
    pub specify_no_mi_for: Option<PackageId>,
    /// Set the given patch file for the given package.
    ///
    /// MAINTAINERS: A target with `TargetKind::InlineTest` will look for
    /// the patch file in `TargetKind::Source` too.
    pub specify_patch_file: Option<(BuildTarget, PathBuf)>,

    /// Emit --enable-value-tracing for the given package's test targets. When
    /// `moon test -p pkg --enable-value-tracing`, this will be set to
    /// `Some(pkg)` so that only `pkg`'s test targets will emit
    /// --enable-value-tracing but not its dependencies' test targets.
    pub value_tracing: Option<PackageId>,

    /// Use the given Why3 config file for `moon prove`.
    pub prove_why3_config: Option<PathBuf>,

    /// Use the proof prelude provider from this directory for `moon prove`.
    pub proof_prelude: PathBuf,

    /// Control package-level prebuild for this invocation.
    pub package_prebuild: PackagePrebuildPolicy,
}

impl Default for InputDirective {
    fn default() -> Self {
        Self {
            specify_no_mi_for: None,
            specify_patch_file: None,
            value_tracing: None,
            prove_why3_config: None,
            proof_prelude: moonutil::toolchain::prelude_proof(),
            package_prebuild: PackagePrebuildPolicy::default(),
        }
    }
}

/// Represents errors that may occur during build graph construction.
#[derive(Debug, thiserror::Error)]
pub enum BuildPlanConstructError {
    #[error("Failed to set C compiler when compiling {1}")]
    FailedToSetCC(#[source] anyhow::Error, PackageFQNWithSource),
    #[error("Failed to set C compiler when compiling runtime")]
    FailedToSetRuntimeCC(#[source] anyhow::Error),
    #[error("Failed to locate runtime C sources")]
    FailedToFindRuntimeSources(#[source] anyhow::Error),
    #[error("Failed to resolve dsymutil when linking {1}")]
    FailedToResolveDsymutil(#[source] anyhow::Error, PackageFQNWithSource),
    #[error("Failed to set stub C compiler when compiling {1}")]
    FailedToSetStubCC(#[source] anyhow::Error, PackageFQNWithSource),
    #[error("Malformed cc flags in package {0}")]
    MalformedCCFlags(PackageFQNWithSource),
    #[error("Malformed cc link flags in package {0}")]
    MalformedCCLinkFlags(PackageFQNWithSource),
    #[error("Malformed stub cc flags in package {0}")]
    MalformedStubCCFlags(PackageFQNWithSource),
    #[error("Malformed stub cc link flags in package {0}")]
    MalformedStubCCLinkFlags(PackageFQNWithSource),
    #[error("Invalid pre-build rule in package {package}: {message}")]
    InvalidPrebuildRule {
        package: PackageFQNWithSource,
        message: String,
    },

    #[error("Cannot find `pkg.mbti` declaration file for virtual package {0}")]
    MissingVirtualMbtiFile(PackageFQNWithSource),

    #[error(
        "Package {package}'s (possibly transitive) dependency {dep} \
        is a virtual package with no default implementation, \
        and no override packages were given to implement it."
    )]
    NoImplementationForVirtualPackage {
        package: PackageFQNWithSource,
        dep: PackageFQNWithSource,
    },

    #[error(
        "Selected backend '{backend}' is incompatible with the dependency graph. \
         '{importer}' requires '{dependency}' which supports {supported_backends}. \
         Dependency path: {path}"
    )]
    BackendIncompatibleDependency {
        backend: TargetBackend,
        importer: String,
        dependency: String,
        supported_backends: String,
        path: String,
    },
}

/// Construct a Build Plan that produces the requested artifacts.
#[instrument(skip_all)]
pub fn build_plan(
    resolved: &ResolveOutput,
    mooncake_bin_dir: &Path,
    build_env: &BuildEnvironment,
    input: impl Iterator<Item = ArtifactKey>,
    input_directive: &InputDirective,
    prebuild_config: Option<&PrebuildOutput>,
    user_log: &UserLog,
) -> Result<BuildPlan, BuildPlanConstructError> {
    info!("Constructing build plan");
    debug!(
        "Build environment: backend={:?}, opt_level={:?}",
        build_env.target_backend(),
        build_env.opt_level
    );

    let mut constructor = BuildPlanConstructor::new(
        resolved,
        mooncake_bin_dir,
        build_env,
        input_directive,
        prebuild_config,
        user_log,
    );
    constructor.build(input)?;
    let result = constructor.finish();

    info!(
        "Build plan construction completed with {} total nodes",
        result.node_count()
    );
    Ok(result)
}
