// moon: The build system and package manager for MoonBit.
// Copyright (C) 2024 International Digital Economy Academy
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// For inquiries, you can contact us via e-mail at jichuruanjian@idea.edu.cn.

use super::*;

#[test]
fn test_moonlex() {
    // Note: previously there's a check about installed `moonlex` binary,
    // but since it comes with the distribution now, we can skip that.
    let dir = TestDir::new("prebuild/moonlex");
    let _ = get_stdout(&dir, ["check"]);
    assert!(dir.join("src/main/fortytwolexer.mbt").exists());
}

#[test]
fn test_pre_build() {
    let dir = TestDir::new("pre_build.in");

    // replace CRLF with LF on Windows
    let b_txt_path = dir.join("src/lib/b.txt");
    std::fs::write(&b_txt_path, read(&b_txt_path)).unwrap();

    // Assert that prebuilt files didn't exist
    assert!(
        !dir.join("src/lib/a.mbt").exists(),
        "Prebuilt file should not exist before execution"
    );

    get_stderr(&dir, ["check"]);
    // should successfully execute

    check(
        read(dir.join("src/lib/a.mbt")),
        expect![[r#"
            // Generated by `moon tool embed --text`, do not edit.

            ///|
            let resource : String =
              #|hello,
              #|world
              #|
        "#]],
    );
    let content = read(dir.join("src/lib/b.mbt"));
    check(
        content,
        expect![[r#"
            // Generated by `moon tool embed --binary`, do not edit.

            ///|
            let _b : Bytes = [
              0x4d, 0x6f, 0x6f, 0x6e, 0x42, 0x69, 0x74, 0x20, 0x69, 0x73, 0x20, 0x61, 
              0x6e, 0x20, 0x65, 0x6e, 0x64, 0x2d, 0x74, 0x6f, 0x2d, 0x65, 0x6e, 0x64, 
              0x20, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d, 0x69, 0x6e, 0x67, 
              0x20, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x20, 0x74, 0x6f, 
              0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x20, 0x66, 0x6f, 0x72, 0x20, 
              0x63, 0x6c, 0x6f, 0x75, 0x64, 0x20, 0x61, 0x6e, 0x64, 0x20, 0x65, 0x64, 
              0x67, 0x65, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x69, 0x6e, 0x67, 
              0x20, 0x75, 0x73, 0x69, 0x6e, 0x67, 0x20, 0x57, 0x65, 0x62, 0x41, 0x73, 
              0x73, 0x65, 0x6d, 0x62, 0x6c, 0x79, 0x2e, 0x20, 0x54, 0x68, 0x65, 0x20, 
              0x49, 0x44, 0x45, 0x20, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 
              0x65, 0x6e, 0x74, 0x20, 0x69, 0x73, 0x20, 0x61, 0x76, 0x61, 0x69, 0x6c, 
              0x61, 0x62, 0x6c, 0x65, 0x20, 0x61, 0x74, 0x0a, 0x68, 0x74, 0x74, 0x70, 
              0x73, 0x3a, 0x2f, 0x2f, 0x74, 0x72, 0x79, 0x2e, 0x6d, 0x6f, 0x6f, 0x6e, 
              0x62, 0x69, 0x74, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x63, 0x6f, 0x6d, 0x20, 
              0x77, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x20, 0x61, 0x6e, 0x79, 0x20, 
              0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 
              0x3b, 0x20, 0x69, 0x74, 0x20, 0x64, 0x6f, 0x65, 0x73, 0x20, 0x6e, 0x6f, 
              0x74, 0x20, 0x72, 0x65, 0x6c, 0x79, 0x20, 0x6f, 0x6e, 0x20, 0x61, 0x6e, 
              0x79, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x20, 0x65, 0x69, 0x74, 
              0x68, 0x65, 0x72, 0x2e, 
            ]
        "#]],
    );
    check(
        read(dir.join("src/lib/c.mbt")),
        expect![[r#"
            // Generated by `moon tool embed --text`, do not edit.

            ///|
            let _c : String =
              #|hello,
              #|world
              #|
        "#]],
    );
}

#[test]
fn test_pre_build_runs_from_module_root() {
    let dir = TestDir::new("pre_build_cwd.in");
    let src_dir = dir.join("src");

    moon_cmd(&src_dir)
        .env("MOON_OVERRIDE", moon_bin())
        .args(["-C", "..", "check", "--sort-input"])
        .assert()
        .success();

    check(
        read(dir.join("src/lib/generated.mbt")),
        expect![[r#"
            // Generated by `moon tool embed --text`, do not edit.

            ///|
            let cwd_marker : String =
              #|module-root-cwd
              #|
        "#]],
    );
}

#[test]
fn test_pre_build_dry_run_uses_cwd_relative_placeholders() {
    let dir = TestDir::new("pre_build.in");
    let assert = moon_cmd(&dir)
        .args(["check", "--dry-run", "--sort-input"])
        .assert()
        .success();
    let stdout = std::str::from_utf8(&assert.get_output().stdout).unwrap();
    let prebuild_lines = stdout
        .lines()
        .filter(|line| line.contains(" tool embed "))
        .collect::<Vec<_>>();

    assert!(
        prebuild_lines
            .iter()
            .any(|line| line.contains(" -i ./src/lib/a.txt -o ./src/lib/a.mbt")),
        "dry-run should show cwd-relative placeholders, got:\n{stdout}"
    );
}

#[test]
fn test_pre_build_dry_run_uses_prebuild_cwd_after_chdir() {
    let dir = TestDir::new("pre_build.in");
    let src_dir = dir.join("src");
    let assert = moon_cmd(&src_dir)
        .args(["-C", "..", "check", "--dry-run", "--sort-input"])
        .assert()
        .success();
    let stdout = std::str::from_utf8(&assert.get_output().stdout).unwrap();
    let prebuild_lines = stdout
        .lines()
        .filter(|line| line.contains(" tool embed "))
        .collect::<Vec<_>>();

    assert!(
        prebuild_lines
            .iter()
            .any(|line| line.contains(" -i ./src/lib/a.txt -o ./src/lib/a.mbt")),
        "dry-run should show placeholders relative to prebuild cwd, got:\n{stdout}"
    );
}

#[test]
#[cfg(unix)]
fn test_rule_dev_build() {
    let dir = TestDir::new("define_rule_dev_build.in");

    assert!(!dir.join("main.mbt").exists());
    assert!(!dir.join("helper.mbt").exists());

    get_stderr(&dir, ["fmt", "--check"]);
    get_stderr(&dir, ["build"]);
    get_stderr(&dir, ["check"]);

    check(
        read(dir.join("main.mbt")),
        expect![[r#"
            fn main { println(helper()) }
        "#]],
    );
    check(
        read(dir.join("helper.mbt")),
        expect![[r#"
            fn helper() -> Int { 42 }
        "#]],
    );
}

#[test]
#[cfg(unix)]
fn test_package_local_rule_dev_build() {
    let dir = TestDir::new("define_pkg_rule_dev_build.in");

    assert!(!dir.join("main.mbt").exists());
    assert!(!dir.join("helper.mbt").exists());

    get_stderr(&dir, ["fmt", "--check"]);
    get_stderr(&dir, ["build"]);
    get_stderr(&dir, ["check"]);

    check(
        read(dir.join("main.mbt")),
        expect![[r#"
            fn main { println(helper()) }
        "#]],
    );
    check(
        read(dir.join("helper.mbt")),
        expect![[r#"
            fn helper() -> Int { 42 }
        "#]],
    );
}

#[test]
fn test_pre_build_mooncake_bin_shape() {
    let top_dir = TestDir::new("pre_build_mooncake_bin_shape.in");
    let dir = top_dir.join("user.in");
    let target_dir = dir.join("artifacts");
    let moon_home = tempfile::TempDir::new().expect("failed to create temp MOON_HOME");
    cache_registry_package(
        moon_home.path(),
        "username/registry_shape_tool",
        "0.1.0",
        &[
            (
                "moon.mod.json",
                br#"{
  "name": "username/registry_shape_tool",
  "version": "0.1.0",
  "source": "src",
  "bin-deps": {
    "username/missing_nested_tool": "0.1.0"
  }
}"#
                .to_vec(),
            ),
            (
                "src/main-js/moon.pkg.json",
                br#"{
  "is-main": true,
  "bin-target": "js",
  "bin-name": "registry-shape-tool",
  "pre-build": [
    {
      "input": [],
      "output": ["generated.mbt"],
      "command": "moon tool write-tcc-rsp-file \"$output\" fn \"generated()->Int{42}\""
    }
  ]
}"#
                .to_vec(),
            ),
            (
                "src/main-js/main.mbt",
                br#"fn main { println(generated()) }"#.to_vec(),
            ),
        ],
    );

    get_stderr_with_envs(
        &dir,
        ["--target-dir", "artifacts", "check"],
        [("MOON_HOME", moon_home.path())],
    );

    #[cfg(unix)]
    let launcher = top_dir.join("provider.in").join("shape-tool");
    #[cfg(target_os = "windows")]
    let launcher = top_dir.join("provider.in").join("shape-tool.ps1");
    assert!(launcher.exists(), "expected bin-dep launcher: {launcher:?}");

    #[cfg(unix)]
    let registry_launcher = target_dir.join(MOON_BIN_DIR).join("registry-shape-tool");
    #[cfg(target_os = "windows")]
    let registry_launcher = target_dir
        .join(MOON_BIN_DIR)
        .join("registry-shape-tool.ps1");
    assert!(
        registry_launcher.exists(),
        "expected registry bin-dep launcher: {registry_launcher:?}"
    );
    assert!(
        !dir.join(".mooncakes")
            .join("username")
            .join("registry_shape_tool")
            .join(registry_launcher.file_name().unwrap())
            .exists(),
        "registry launcher must not make mooncakes_dir mutable"
    );
    let registry_source = dir
        .join(".mooncakes")
        .join("username")
        .join("registry_shape_tool");
    assert!(
        !registry_source.join(BUILD_DIR).exists(),
        "registry bin-dep build must not write under mooncakes_dir"
    );
    assert!(
        !registry_source.join("src/main-js/generated.mbt").exists(),
        "registry bin-dep pre-build must not write under mooncakes_dir"
    );
    let bin_dep_temp_dirs = std::fs::read_dir(&target_dir)
        .unwrap()
        .filter_map(Result::ok)
        .filter(|entry| entry.file_name().to_string_lossy().starts_with(".bin-dep-"))
        .collect::<Vec<_>>();
    assert!(
        bin_dep_temp_dirs.is_empty(),
        "registry bin-dep temporary work directories must be removed"
    );

    let installed_artifacts = target_dir
        .join(MOON_BIN_DIR)
        .join(".artifacts")
        .join("registry-shape-tool");
    assert!(
        installed_artifacts.is_dir(),
        "registry bin-dep artifact must be copied out of the temporary build"
    );
    let installed_artifacts = dunce::canonicalize(&installed_artifacts)
        .expect("failed to canonicalize installed registry bin-dep artifact directory");
    let launcher_contents = read(&registry_launcher).replace('\\', "/");
    let installed_artifacts = installed_artifacts.to_string_lossy().replace('\\', "/");
    // Windows launchers escape path separators as `//`; normalize them before
    // checking that the launcher points at the stable copied artifact.
    let normalized_launcher_contents = launcher_contents.replace("//", "/");
    assert!(
        normalized_launcher_contents.contains(&installed_artifacts),
        "registry launcher must reference the copied artifact directory `{installed_artifacts}`; \
         launcher contents: {launcher_contents:?}"
    );
    assert!(
        !launcher_contents.contains(".bin-dep-"),
        "registry launcher must not reference a temporary build directory"
    );

    #[cfg(unix)]
    {
        let output = std::process::Command::new(&registry_launcher)
            .output()
            .expect("failed to run installed registry bin-dep");
        assert!(
            output.status.success(),
            "installed registry bin-dep failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        assert_eq!(String::from_utf8_lossy(&output.stdout).trim(), "42");
    }

    let actual_raw = read(dir.join("src/main/mooncake_bin.txt"));
    let actual_path = actual_raw.trim();
    let actual_path = actual_path
        .strip_prefix('"')
        .and_then(|s| s.strip_suffix('"'))
        .unwrap_or(actual_path)
        .replace("\\\"", "\"")
        .replace('\\', "/");

    let expected_path = dunce::canonicalize(&target_dir)
        .unwrap()
        .join(MOON_BIN_DIR)
        .to_string_lossy()
        .replace('\\', "/");

    assert_eq!(actual_path, expected_path);
}

#[test]
fn test_pre_build_ignore_prebuild_env() {
    let dir = TestDir::new("pre_build.in");

    // replace CRLF with LF on Windows
    let b_txt_path = dir.join("src/lib/b.txt");
    std::fs::write(&b_txt_path, read(&b_txt_path)).unwrap();

    assert!(
        !dir.join("src/lib/a.mbt").exists(),
        "Prebuilt file should not exist before execution"
    );

    let stderr = get_err_stderr_with_envs(&dir, ["check"], [("MOON_IGNORE_PREBUILD", "1")]);

    assert!(
        stderr.contains("a.mbt"),
        "expected missing generated source in stderr, got:\n{stderr}"
    );
    assert!(
        !dir.join("src/lib/a.mbt").exists(),
        "`MOON_IGNORE_PREBUILD` should not generate prebuild outputs"
    );
}

#[test]
#[cfg(unix)]
fn test_pre_build_dirty() {
    let dir = TestDir::new("pre_build_dirty.in");

    // Assert prebuild runs by checking file existence
    let file = dir.join("src/lib/a.mbt");

    assert!(!file.exists(), "prebuild.txt should not exist yet");
    let _first_prebuild = get_stderr(&dir, ["check"]);
    assert!(file.exists(), "prebuild.txt should exist after prebuild");
    let mtime = file.metadata().unwrap().modified().unwrap();

    check(
        get_stderr(&dir, ["check"]),
        expect![[r#"
            Finished. moon: no work to do
        "#]],
    );
    check(
        get_stderr(&dir, ["check"]),
        expect![[r#"
            Finished. moon: no work to do
        "#]],
    );

    let mtime_end = file.metadata().unwrap().modified().unwrap();
    assert_eq!(mtime, mtime_end, "file should not be modified");
}
