// moon: The build system and package manager for MoonBit.
// Copyright (C) 2026 International Digital Economy Academy
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
// either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// For inquiries, you can contact us via e-mail at jichuruanjian@idea.edu.cn.

static PANIC_BUG_REPORT_MSG: &str = r"
         --  -- 
       /  //  / __--------_
      /  //  /_/            \
   ---      -                \ __
  / X        /        ____   /   )
  *_________/__/_____/______/ `--

`moon` has accidentally crashed. 

This is likely a bug in `moon`. We appreciate a bug report containing the panic
message and locations reported above, and what you have done to trigger it.
A backtrace generated by running with `RUST_BACKTRACE=1` would also be helpful.

Please report it at:
    https://github.com/moonbitlang/moon/issues/new?template=bug_report.md
";

/// Set up a hook when `moon` panics, to suggest reporting bugs.
pub(crate) fn setup_panic_hook() {
    let default_panic_hook = std::panic::take_hook();
    std::panic::set_hook(Box::new(move |info| {
        default_panic_hook(info);
        eprintln!("{}", PANIC_BUG_REPORT_MSG);
    }));
}
