# moon: The build system and package manager for MoonBit.
# Copyright (C) 2024 International Digital Economy Academy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# For inquiries, you can contact us via e-mail at jichuruanjian@idea.edu.cn.

[package]
name = "moon"
version = "0.1.0"
edition.workspace = true
exclude = [".github/*", ".vscode/*"]
readme = "README.md"
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anstream.workspace = true
anstyle.workspace = true
moonbuild.workspace = true
mooncake.workspace = true
moonutil.workspace = true
moonbuild-rupes-recta.workspace = true

n2.workspace = true
semver.workspace = true
clap.workspace = true
anyhow.workspace = true
colored.workspace = true
serde.workspace = true
serde_json_lenient.workspace = true
serde_json.workspace = true
dunce.workspace = true
ctrlc.workspace = true
home.workspace = true
which.workspace = true
chrono.workspace = true
log.workspace = true
walkdir.workspace = true
notify.workspace = true
tokio = { workspace = true, features = ["rt", "signal"] }
tokio-util.workspace = true
clap_complete.workspace = true
indexmap.workspace = true
petgraph.workspace = true
rand.workspace = true
tempfile.workspace = true
unicode-width.workspace = true
shlex.workspace = true
derive_builder.workspace = true
sha2.workspace = true
blake3.workspace = true

ignore.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true
tracing-chrome.workspace = true

[target."cfg(target_os = \"macos\")".dependencies]
libc.workspace = true

[target."cfg(windows)".dependencies.windows-sys]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Console",
    "Win32_System_JobObjects",
    "Win32_System_Threading",
]

[target."cfg(windows)".dependencies]
junction.workspace = true

[dev-dependencies]
regex.workspace = true
snapbox = { workspace = true, features = ["regex"] }
expect-test.workspace = true
escargot.workspace = true
clap-markdown.workspace = true
similar.workspace = true
libc.workspace = true
moonbuild-debug.workspace = true
moon-test-util.workspace = true
zip.workspace = true


[[bin]]
name = "moon"
bench = false
