# moon: The build system and package manager for MoonBit.
# Copyright (C) 2026 International Digital Economy Academy
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For inquiries, you can contact us via e-mail at jichuruanjian@idea.edu.cn.

[package]
name = "moonbuild"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
n2.workspace = true
ariadne.workspace = true
blake3.workspace = true
tracing.workspace = true
anstream.workspace = true
anstyle.workspace = true
moonutil.workspace = true
moonbuild-rupes-recta.workspace = true
clap.workspace = true
serde.workspace = true
serde_json_lenient.workspace = true
anyhow.workspace = true
colored.workspace = true
dunce.workspace = true
indexmap.workspace = true
ctrlc.workspace = true
similar.workspace = true
line-index.workspace = true
tokio.workspace = true
text-size.workspace = true
hyper.workspace = true
hyper-util.workspace = true
hyper-staticfile.workspace = true
http.workspace = true
dialoguer.workspace = true
reqwest.workspace = true
json-structural-diff.workspace = true
base64.workspace = true
serde_json.workspace = true
handlebars.workspace = true
toml = { workspace = true, features = ["parse", "serde", "std"] }

[dev-dependencies]
tempfile.workspace = true

[target."cfg(windows)".dependencies]
self-replace.workspace = true
tempfile.workspace = true
