// moon: The build system and package manager for MoonBit.
// Copyright (C) 2026 International Digital Economy Academy
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
// either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// For inquiries, you can contact us via e-mail at jichuruanjian@idea.edu.cn.

use std::path::PathBuf;

use anyhow::Context;

#[derive(Debug, clap::Parser)]
#[clap(group = clap::ArgGroup::new("embed_mode").multiple(false))]
pub(crate) struct Embed {
    #[clap(long, group = "embed_mode")]
    binary: bool,
    #[clap(long, group = "embed_mode")]
    text: bool,
    #[clap(long, short)]
    input: PathBuf,
    #[clap(long, short)]
    output: PathBuf,
    #[clap(long)]
    name: Option<String>,
    #[clap(long)]
    timestamp: bool,
}

pub(crate) fn run_embed_text(cmd: Embed) -> anyhow::Result<i32> {
    let input = std::fs::read_to_string(&cmd.input)?;
    let name = cmd.name.unwrap_or_else(|| "resource".to_string());
    let mut content = format!(
        r#"// Generated by `moon tool embed --text`{}, do not edit.

///|
let {} : String =
"#,
        if cmd.timestamp {
            format!(" on {}", chrono::Local::now().format("%Y-%m-%d %H:%M:%S"))
        } else {
            String::new()
        },
        name
    );
    for line in input.split('\n') {
        content.push_str(&format!("  #|{line}\n"));
    }
    std::fs::write(cmd.output, content).context("write output file")?;
    Ok(0)
}

pub(crate) fn run_embed_bin(cmd: Embed) -> anyhow::Result<i32> {
    let input = std::fs::read(&cmd.input)?;
    let name = cmd.name.unwrap_or_else(|| "resource".to_string());
    let mut content = format!(
        r#"// Generated by `moon tool embed --binary`{}, do not edit.

///|
let {} : Bytes = [
"#,
        if cmd.timestamp {
            format!(" on {}", chrono::Local::now().format("%Y-%m-%d %H:%M:%S"))
        } else {
            String::new()
        },
        name
    );

    for (i, byte) in input.iter().enumerate() {
        if i % 12 == 0 {
            if i > 0 {
                content.push('\n');
            }
            content.push_str("  ");
        }
        content.push_str(&format!("0x{byte:02x}, "));
    }
    content.push_str("\n]\n");
    std::fs::write(cmd.output, content).context("write output file")?;
    Ok(0)
}

pub(crate) fn run_embed(cmd: Embed) -> anyhow::Result<i32> {
    if cmd.binary {
        run_embed_bin(cmd)
    } else {
        run_embed_text(cmd)
    }
}
