/// ```
/// println("doc_test 1 from greet.mbt")
/// ```
pub fn greet1() -> String {
  "greet, world!"
}


/// ```
/// println("doc_test 2 from greet.mbt")
/// 
/// 
/// 
/// ```
pub fn greet2() -> String {
  "greet, world!"
}

/// ```
/// println("doc_test 3 from greet.mbt")
/// 
/// 
/// 
/// ```
pub fn greet3() -> String {
  "greet, wor1ld!"
}

/// ```
/// println("doc_test from greet.mbt")
/// 
/// 
/// inspect!(423)
/// 
/// ```
pub fn greet() -> String {
  "greet, wor1ld!"
}
