/// ```
/// println("doc_test 1 from hello.mbt")
/// ```
pub fn hello1() -> String {
  "Hello, world!"
}


/// ```
/// println("doc_test 2 from hello.mbt")
/// 
/// 
/// 
/// ```
pub fn hello2() -> String {
  "Hello, world!"
}

/// ```
/// println("doc_test 3 from hello.mbt")
/// 
/// fail!("this is a failure")
/// 
/// ```
pub fn hello3() -> String {
  "Hello, wor1ld!"
}

/// ```
/// println("doc_test")
/// 
/// 
/// 
/// 
/// 
/// assert_true!(true)
/// ```
pub fn hello() -> String {
  "Hello, wor1ld!"
}
