/// ```
/// println("doc_test 1 from hello.mbt")
/// ```
pub fn hello1() -> String {
  "Hello, world!"
}


/// ```mbt
/// println("doc_test 2 from hello.mbt")
/// 
/// inspect(1256)
/// 
/// ```
pub fn hello2() -> String {
  "Hello, world!"
}

/// ```
/// println("doc_test 3 from hello.mbt")
/// 
/// fail("this is a failure")
/// 
/// ```
pub fn hello3() -> String {
  "Hello, wor1ld!"
}

/// ```
/// println("doc_test")
/// 
/// 
/// 
/// 
/// 
/// assert_true!(true)
/// ```
pub fn hello() -> String {
  "Hello, wor1ld!"
}


/// ```no-run
/// 
/// assert_true!(true)
/// ```
/// 
/// this is comment
/// 
/// 
/// ```python
/// 
/// 
/// ```
/// 
/// 
/// 
/// 
/// ```
/// 
/// assert_true!(true)
/// ```
/// 
/// this is comment
/// 
/// 
/// ```
/// 
/// assert_true!(true)
/// ```
pub fn fasd() -> String {
  "Hello, wor1ld!"
}
