# moon: The build system and package manager for MoonBit.
# Copyright (C) 2026 International Digital Economy Academy
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For inquiries, you can contact us via e-mail at jichuruanjian@idea.edu.cn.

name: Check for Merge Commits

on:
  pull_request:
    branches: main

jobs:
  check-merge-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v6
  
    - name: Get all commit messages
      id: get-commit-messages
      uses: actions/github-script@v9
      with:
        script: |
          // If this commit is not part of a PR (e.g. in merge queue check),
          // skip the rest
          if (context && context.payload && context.payload.pull_request) {
            const prNumber = context.payload.pull_request.number;
            const commits = await github.rest.pulls.listCommits({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
                per_page: 100
            });
            const commitMessages = commits.data.map(commit => commit.commit.message);
            const hasMergeCommit = commitMessages.some(message => message.startsWith('Merge branch') || message.startsWith('Merge pull request'));
            if (hasMergeCommit) {
                core.setFailed('Pull request contains merge commit(s).');
            }
          }

    - name: Check for merge commits
      if: failure()
      run: echo "This pull request contains merge commit(s) and has been marked as failed."
